# Generated by Django 5.2.8 on 2026-03-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20)),
                ('sem', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
